
language: c++
sudo: required

matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          packages:
            - g++-5
            - gfortran-5
          sources: &sources
            - ubuntu-toolchain-r-test
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5 && FC=gfortran-5"
      compiler: gcc
    
    - os: linux
      dist: trusty
      addons:
        apt:
          packages:
            - g++-6
            - gfortran-6
          sources: &sources
            - ubuntu-toolchain-r-test
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6 && FC=gfortran-6"
      compiler: gcc

    - os: linux
      dist: trusty
      addons:
        apt:
          packages:
            - g++-7
            - gfortran-7
          sources: &sources
            - ubuntu-toolchain-r-test
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && FC=gfortran-7"
      compiler: gcc

    - os: linux
      dist: trusty
      addons:
        apt:
          packages:
            - clang-5.0
            - gfortran-7
          sources: &sources
            - llvm-toolchain-trusty-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0 && FC=gfortran-7"
      compiler: clang

before_install:
    - export FC=gfortran
    - eval "${MATRIX_EVAL}"

install:
    - |
      if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
        sudo apt-get update
        sudo apt-get install libblas-dev liblapack-dev
      else
        # OSX
        brew upgrade gcc || brew install gcc
      fi

script:
  - cd ./tests
  - ./cov_setup
  - cd ..

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
