
language: c++
sudo: required

branches:
  except: /pr\/.*/

addons:
  apt:
    packages:
      - g++-6
      - gfortran-6
    sources: &sources
      - ubuntu-toolchain-r-test

matrix:
  include:
    - os: linux
      dist: trusty
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6 && FC=gfortran-6"
      compiler: gcc

    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
      compiler: clang

before_install:
    -  eval "${MATRIX_EVAL}"

install:
    - sudo apt-get update
    - sudo apt-get install libblas-dev liblapack-dev

script:
  - cd ./tests
  - ./cov_setup
  - cd ..

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
